on:
  push:
    branches: [ master ]
name: Publish DEV site
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_DEV_ADDRESS }}
        ftp-username: ${{ secrets.FTP_DEV_USER }}
        ftp-password: ${{ secrets.FTP_DEV_PASS }}
        git-ftp-args: --dry-run 
